basePath: '{{.BasePath}}'
definitions:
  entities.Advertisement:
    properties:
      IsActive:
        type: boolean
      advertiserId:
        type: integer
      banners:
        items:
          $ref: '#/definitions/entities.Banner'
        type: array
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  entities.Advertiser:
    properties:
      contactInfo:
        type: string
      createdAt:
        example: "2018-10-30T19:43:15.251038Z"
        type: string
      email:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      notes:
        type: string
      password:
        type: string
      role:
        type: integer
      updatedAt:
        example: "2018-10-30T19:43:15.251038Z"
        type: string
      username:
        type: string
    type: object
  entities.Banner:
    properties:
      advertisementId:
        type: integer
      bannerPlaceId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      isVisible:
        type: boolean
      pictureUrl:
        type: string
      text:
        type: string
      uniqueViews:
        type: integer
      uniqueViewsRequired:
        type: integer
      updatedAt:
        type: string
      views:
        type: integer
    type: object
  responses.AllAdvertisements:
    properties:
      advertisements:
        items:
          $ref: '#/definitions/entities.Advertisement'
        type: array
      count:
        example: 0
        type: integer
      status:
        example: OK
        type: string
    type: object
  responses.AllAdvertisers:
    properties:
      advertisers:
        items:
          $ref: '#/definitions/entities.Advertiser'
        type: array
      count:
        example: 0
        type: integer
      status:
        example: OK
        type: string
    type: object
  responses.OneAdvertisement:
    properties:
      advertisement:
        $ref: '#/definitions/entities.Advertisement'
        type: object
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /ads:
    get:
      description: Метод возвращает данные о всех рекламных объявлениях
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AllAdvertisements'
            type: object
        "422": {}
      summary: Получить вообще все рекламные объявления
      tags:
      - Advertisements
    post:
      consumes:
      - application/json
      description: Метод добавляет новое рекламне объявление с заданными параметрами
      parameters:
      - description: Данные о рекламном объявлении
        in: body
        name: advertisement
        required: true
        schema:
          $ref: '#/definitions/entities.Advertisement'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.OneAdvertisement'
            type: object
        "422": {}
      summary: Добавить рекламное объявление
      tags:
      - Advertisements
  /ads/{id}:
    delete:
      description: Метод удаляет рекламне объявление с заданным ID
      parameters:
      - description: ID рекламного объявления
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
        "422": {}
      summary: Удалить рекламное объявление
      tags:
      - Advertisements
    get:
      description: Метод возвращает данные рекламном объявлении с данным ID
      parameters:
      - description: ID рекламного объявления
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.OneAdvertisement'
            type: object
        "404": {}
        "422": {}
      summary: Получить рекламное объявление по ID
      tags:
      - Advertisements
    put:
      consumes:
      - application/json
      description: Метод обновляет рекламне объявление с заданным ID
      parameters:
      - description: ID рекламного объявления
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные о рекламном объявлении
        in: body
        name: advertisement
        required: true
        schema:
          $ref: '#/definitions/entities.Advertisement'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.OneAdvertisement'
            type: object
        "404": {}
        "422": {}
      summary: Обновить рекламное объявление
      tags:
      - Advertisements
  /advertiser/{id}/ads:
    get:
      description: Метод возвращает данные о рекламных объявлениях рекламодателя с
        заданным ID
      parameters:
      - description: ID рекламодателя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AllAdvertisements'
            type: object
        "422": {}
      summary: Получить рекламные объявления рекламодателя
      tags:
      - Advertisements
  /advertisers:
    get:
      description: Метод возвращает список всех имеющихся в системе рекламодателей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AllAdvertisers'
            type: object
      summary: Получить список всех рекламодателей
      tags:
      - Advertisers
    post:
      consumes:
      - application/json
      description: Метод добавляет в систему нового рекламодателя с заданными параметрами
      parameters:
      - description: Данные о рекламодателе
        in: body
        name: advertiser
        required: true
        schema:
          $ref: '#/definitions/entities.Advertiser'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: '{"advertiser": entities.Advertiser}'
          schema:
            $ref: '#/definitions/entities.Advertiser'
            type: object
        "422": {}
      summary: Добавить нового рекламодателя
      tags:
      - Advertisers
  /advertisers/{id}:
    delete:
      description: Метод удаляет из системы рекламодателя с заданным ID
      parameters:
      - description: ID рекламодателя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
        "422": {}
      summary: Удалить рекламодателя
      tags:
      - Advertisers
    get:
      description: Метод возвращает рекламодателя по его ID
      parameters:
      - description: ID рекламодателя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"advertiser": entities.Advertiser}'
          schema:
            $ref: '#/definitions/entities.Advertiser'
            type: object
        "404":
          description: '{"message": "resource not found"}'
        "422": {}
      summary: Получить рекламодателя по ID
      tags:
      - Advertisers
    put:
      consumes:
      - application/json
      description: Метод обновляет рекламодателя заданными параметрами по ID
      parameters:
      - description: ID рекламодателя
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные о рекламодателе
        in: body
        name: advertiser
        required: true
        schema:
          $ref: '#/definitions/entities.Advertiser'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"advertiser": entities.Advertiser}'
          schema:
            $ref: '#/definitions/entities.Advertiser'
            type: object
        "404": {}
        "422": {}
      summary: Обновить рекламодателя
      tags:
      - Advertisers
swagger: "2.0"
