info:
  contact: {}
  license: {}
paths:
  /advertisers:
    get:
      description: Список рекламодателей
      produces:
      - application/json
      responses:
        "200":
          description: '{"advertisers":[],"count":0,"status":"OK"}'
      summary: Получить список всех рекламодателей
