[metadata.heroku]
  root-package = "github.com/a1ta1r/credit-portfolio"
  install = "./..."

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
