[metadata.heroku]
  root-package = "github.com/credit-portfolio/main"
  insall = ["./cmd/..."]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
