[metadata.heroku]
  root-package = "github.com/a1ta1r/Credit-Portfolio"
  install = "./..."

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2"

[prune]
  go-tests = true
  unused-packages = true

[[required]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[required]]
  name = "github.com/swaggo/gin-swagger"
  version = "1.0.0"

[[required]]
  name = "github.com/swaggo/gin-swagger/swaggerFiles"
  version = "1.0.0"